/* tslint:disable */
/* eslint-disable */
/**
 * Fanno Platform API
 * AI-driven platform automation API for agent orchestration
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@fanno.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AnnotateRequest,
  AnnotateResponse,
} from '../models/index';
import {
    AnnotateRequestFromJSON,
    AnnotateRequestToJSON,
    AnnotateResponseFromJSON,
    AnnotateResponseToJSON,
} from '../models/index';

export interface AnnotateTextRequest {
    annotateRequest: AnnotateRequest;
}

/**
 * 
 */
export class AIServicesApi extends runtime.BaseAPI {

    /**
     * Annotate text with AI insights
     */
    async annotateTextRaw(requestParameters: AnnotateTextRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AnnotateResponse>> {
        if (requestParameters['annotateRequest'] == null) {
            throw new runtime.RequiredError(
                'annotateRequest',
                'Required parameter "annotateRequest" was null or undefined when calling annotateText().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/annotate`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AnnotateRequestToJSON(requestParameters['annotateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AnnotateResponseFromJSON(jsonValue));
    }

    /**
     * Annotate text with AI insights
     */
    async annotateText(requestParameters: AnnotateTextRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AnnotateResponse> {
        const response = await this.annotateTextRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
