/* tslint:disable */
/* eslint-disable */
/**
 * Fanno Platform API
 * AI-driven platform automation API for agent orchestration
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@fanno.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Repository,
} from '../models/index';
import {
    RepositoryFromJSON,
    RepositoryToJSON,
} from '../models/index';

/**
 * 
 */
export class OrganizationApi extends runtime.BaseAPI {

    /**
     * Get GitHub repositories
     */
    async getRepositoriesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Repository>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/repositories`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(RepositoryFromJSON));
    }

    /**
     * Get GitHub repositories
     */
    async getRepositories(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Repository>> {
        const response = await this.getRepositoriesRaw(initOverrides);
        return await response.value();
    }

}
