/* tslint:disable */
/* eslint-disable */
/**
 * Fanno Platform API
 * AI-driven platform automation API for agent orchestration
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@fanno.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlatformStats
 */
export interface PlatformStats {
    /**
     * Number of active AI agents
     * @type {number}
     * @memberof PlatformStats
     */
    activeAgents: number;
    /**
     * Number of completed tasks
     * @type {number}
     * @memberof PlatformStats
     */
    completedTasks: number;
    /**
     * Overall setup progress percentage
     * @type {number}
     * @memberof PlatformStats
     */
    progress: number;
}

/**
 * Check if a given object implements the PlatformStats interface.
 */
export function instanceOfPlatformStats(value: object): value is PlatformStats {
    if (!('activeAgents' in value) || value['activeAgents'] === undefined) return false;
    if (!('completedTasks' in value) || value['completedTasks'] === undefined) return false;
    if (!('progress' in value) || value['progress'] === undefined) return false;
    return true;
}

export function PlatformStatsFromJSON(json: any): PlatformStats {
    return PlatformStatsFromJSONTyped(json, false);
}

export function PlatformStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlatformStats {
    if (json == null) {
        return json;
    }
    return {
        
        'activeAgents': json['activeAgents'],
        'completedTasks': json['completedTasks'],
        'progress': json['progress'],
    };
}

export function PlatformStatsToJSON(json: any): PlatformStats {
    return PlatformStatsToJSONTyped(json, false);
}

export function PlatformStatsToJSONTyped(value?: PlatformStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'activeAgents': value['activeAgents'],
        'completedTasks': value['completedTasks'],
        'progress': value['progress'],
    };
}

