/* tslint:disable */
/* eslint-disable */
/**
 * Fanno Platform API
 * AI-driven platform automation API for agent orchestration
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@fanno.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnnotateResponse
 */
export interface AnnotateResponse {
    /**
     * List of AI-generated annotations for the text
     * @type {Array<string>}
     * @memberof AnnotateResponse
     */
    annotations: Array<string>;
}

/**
 * Check if a given object implements the AnnotateResponse interface.
 */
export function instanceOfAnnotateResponse(value: object): value is AnnotateResponse {
    if (!('annotations' in value) || value['annotations'] === undefined) return false;
    return true;
}

export function AnnotateResponseFromJSON(json: any): AnnotateResponse {
    return AnnotateResponseFromJSONTyped(json, false);
}

export function AnnotateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnnotateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'annotations': json['annotations'],
    };
}

export function AnnotateResponseToJSON(json: any): AnnotateResponse {
    return AnnotateResponseToJSONTyped(json, false);
}

export function AnnotateResponseToJSONTyped(value?: AnnotateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'annotations': value['annotations'],
    };
}

