/* tslint:disable */
/* eslint-disable */
/**
 * Fanno Platform API
 * AI-driven platform automation API for agent orchestration
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@fanno.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnnotateRequest
 */
export interface AnnotateRequest {
    /**
     * Text to be annotated
     * @type {string}
     * @memberof AnnotateRequest
     */
    text: string;
}

/**
 * Check if a given object implements the AnnotateRequest interface.
 */
export function instanceOfAnnotateRequest(value: object): value is AnnotateRequest {
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function AnnotateRequestFromJSON(json: any): AnnotateRequest {
    return AnnotateRequestFromJSONTyped(json, false);
}

export function AnnotateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnnotateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'],
    };
}

export function AnnotateRequestToJSON(json: any): AnnotateRequest {
    return AnnotateRequestToJSONTyped(json, false);
}

export function AnnotateRequestToJSONTyped(value?: AnnotateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
    };
}

