
name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install root dependencies
        run: npm ci

      - name: Build SDK
        run: npm run build

      - name: Start payments service in background
        run: npm run serve &

      - name: Wait for service to be ready
        run: npx wait-on http://localhost:5000/health

      - name: Run E2E Smoke Test
        run: node scripts/e2e-test.js

      - name: Notify Orchestrator
        env:
          ORCHESTRATOR_URL: ${{ secrets.ORCHESTRATOR_URL }}
          SDK_VERSION: "1.0.1"
        run: |
          curl -X POST "$ORCHESTRATOR_URL/agent-events" \
            -H "Content-Type: application/json" \
            -d '{
              "agent": "payment-specialist",
              "status": "completed",
              "version": "'"${SDK_VERSION}"'"
            }'
