name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build (if any)
        run: npm run build

      - name: Run E2E Smoke Test
        run: |
          npm install node-fetch@2
          node scripts/e2e-test.js
