
name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install root dependencies
        run: npm ci

      - name: Build SDK
        run: npm run build

      - name: Start payments service in background
        run: npm run serve &

      - name: Wait for service to be ready
        run: npx wait-on http://localhost:5000/health

      - name: Run E2E Smoke Test
        run: node scripts/e2e-test.js
