
name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build SDK
        run: npm run build

      - name: Start payments server & wait
        # Start the server in the background and wait until it's ready
        run: |
          npx concurrently --kill-others \
            "npm run dev" \
            "npx wait-on http://localhost:5000/health"

      - name: Run E2E Smoke Test
        run: node scripts/e2e-test.js
