name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '18'

jobs:
  test:
    name: Test and Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Build SDK
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Start service for health check
        run: npm run serve &

      - name: Wait for service to be ready
        run: npx wait-on http://localhost:5000/health --timeout 30000

      - name: Run health check
        run: |
          response=$(curl -s http://localhost:5000/health)
          echo "Health check response: $response"
          echo "$response" | grep -q '"status":"healthy"' || exit 1

      - name: Run smoke test (create checkout session)
        run: |
          response=$(curl -s -X POST http://localhost:5000/payments/create-session \
            -H "Content-Type: application/json" \
            -d '{"amount": 1000, "currency": "usd"}')
          echo "Create session response: $response"
          echo "$response" | grep -q '"sessionId"' || exit 1

  docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: fanno/payments:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test Docker image
        run: |
          docker run --rm -d --name payments-test -p 5001:5000 fanno/payments:test
          sleep 10
          curl -f http://localhost:5001/health || exit 1
          docker stop payments-test